name: CI

on: [ push, pull_request ]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ 8.3, 8.2, 8.1, 8.0 ]
        release: [ stable, lowest ]

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: bcmath, ctype, json, mbstring, openssl tokenizer, xml, zip
      - name: Install dependencies
        run: composer update --no-interaction --no-progress --prefer-dist --prefer-${{ matrix.release }}
      - name: Run tests
        run: vendor/bin/phpunit
